In [1]:
import numpy as np

# Generar un array NumPy con datos financieros simulados (Precio acciones por dias)

# Número de días a simular
num_days = 100

# Precio inicial de la acción
initial_price = 50.0

# Generar cambios porcentuales diarios aleatorios (pequeñas fluctuaciones)
daily_returns = np.random.normal(0.001, 0.01, num_days) # Media de 0.1% de retorno, desviación estándar de 1%

# Calcular los precios acumulados
simulated_prices = initial_price * np.exp(np.cumsum(daily_returns))

print("Precios de acciones simulados (primeros 10 días):")
print(simulated_prices[:10])
print(f"\nTotal de {num_days} precios simulados.")



Precios de acciones simulados (primeros 10 días):
[49.82273951 50.2198607  50.72188949 50.54495966 51.11515368 51.9134767
 51.80202026 51.73197532 50.9109288  50.9086781 ]

Total de 100 precios simulados.


In [2]:
import numpy as np

# Tomar los primeros 25 elementos para formar la matriz 5x5
prices_for_matrix = simulated_prices[:25]

# Organizar los datos en una matriz de 5x5
stock_prices_matrix = prices_for_matrix.reshape(5, 5)

print("Matriz de precios de acciones (5x5):")
print(stock_prices_matrix)

Matriz de precios de acciones (5x5):
[[49.82273951 50.2198607  50.72188949 50.54495966 51.11515368]
 [51.9134767  51.80202026 51.73197532 50.9109288  50.9086781 ]
 [50.28379341 49.5411254  50.31861097 51.09204885 51.64904125]
 [51.09377364 50.93227905 50.4836149  50.54003747 50.50789564]
 [50.1672223  50.43684225 50.142282   51.28403024 51.69071212]]


In [3]:
import numpy as np

print("Estadísticas por acción (fila):")
for i, row in enumerate(stock_prices_matrix):
    avg_price = np.mean(row)
    max_price = np.max(row)
    min_price = np.min(row)
    print(f"  Acción {i+1}: Promedio = {avg_price:.2f}, Máximo = {max_price:.2f}, Mínimo = {min_price:.2f}")

Estadísticas por acción (fila):
  Acción 1: Promedio = 50.48, Máximo = 51.12, Mínimo = 49.82
  Acción 2: Promedio = 51.45, Máximo = 51.91, Mínimo = 50.91
  Acción 3: Promedio = 50.58, Máximo = 51.65, Mínimo = 49.54
  Acción 4: Promedio = 50.71, Máximo = 51.09, Mínimo = 50.48
  Acción 5: Promedio = 50.74, Máximo = 51.69, Mínimo = 50.14


In [5]:
import numpy as np

print("Variación porcentual diaria por acción (fila):")
for i, row in enumerate(stock_prices_matrix):
    # Calcula la variación porcentual diaria
    # (Precio_actual - Precio_anterior) / Precio_anterior * 100
    daily_percentage_change = (np.diff(row) / row[:-1]) * 100
    # Aquí lo imprimimos directamente para mostrar todos los valores.
    print(f"  Acción {i+1}: {daily_percentage_change}")

Variación porcentual diaria por acción (fila):
  Acción 1: [ 0.79706816  0.99966184 -0.34882342  1.12809274]
  Acción 2: [-0.21469655 -0.13521662 -1.58711612 -0.00442085]
  Acción 3: [-1.47695305  1.56937406  1.53708115  1.09017431]
  Acción 4: [-0.31607489 -0.88090335  0.11176412 -0.06359676]
  Acción 5: [ 0.53744246 -0.58401803  2.2770169   0.79299907]


In [6]:
import numpy as np

print("Aplicando funciones matemáticas a stock_prices_matrix:")

# Aplicar logaritmo natural (np.log) a los precios de las acciones
# Es importante asegurarse de que no haya valores <= 0 antes de aplicar log
log_stock_prices = np.log(stock_prices_matrix)
print("\nMatriz de precios de acciones (logaritmo natural):")
print(log_stock_prices)

# Aplicar función exponencial (np.exp) a los precios de las acciones
# (Esto "deshace" un logaritmo, o simplemente muestra el efecto de exp)
exp_stock_prices = np.exp(stock_prices_matrix)
print("\nMatriz de precios de acciones (exponencial):")
print(exp_stock_prices)

# Normalización Min-Max para cada acción (fila)
normalized_stock_prices = np.zeros_like(stock_prices_matrix, dtype=float)
for i, row in enumerate(stock_prices_matrix):
    min_val = np.min(row)
    max_val = np.max(row)
    # Evitar división por cero si max_val == min_val
    if (max_val - min_val) != 0:
        normalized_stock_prices[i, :] = (row - min_val) / (max_val - min_val)
    else:
        normalized_stock_prices[i, :] = 0.0 # O 0.5 si todos los valores son iguales y se desea el centro

print("\nMatriz de precios de acciones (Normalización Min-Max por fila):")
print(normalized_stock_prices)

Aplicando funciones matemáticas a stock_prices_matrix:

Matriz de precios de acciones (logaritmo natural):
[[3.9084715  3.91641058 3.92635756 3.92286323 3.934081  ]
 [3.94957842 3.94742915 3.94607607 3.93007761 3.9300334 ]
 [3.91768283 3.90280314 3.91837501 3.93362889 3.94447163]
 [3.93366264 3.93049689 3.92164883 3.92276584 3.92212967]
 [3.91536187 3.92072191 3.9148646  3.9373794  3.94527812]]

Matriz de precios de acciones (exponencial):
[[4.34251015e+21 6.45964104e+21 1.06717764e+22 8.94122590e+21
  1.58135431e+22]
 [3.51347177e+22 3.14290715e+22 2.93029550e+22 1.28924497e+22
  1.28634654e+22]
 [6.88611084e+21 3.27670532e+21 7.13009113e+21 1.54523625e+22
  2.69707864e+22]
 [1.54790375e+22 1.31706662e+22 8.40921348e+21 8.89732364e+21
  8.61589447e+21]
 [6.12841007e+21 8.02494890e+21 5.97745594e+21 1.87228235e+22
  2.81184281e+22]]

Matriz de precios de acciones (Normalización Min-Max por fila):
[[0.         0.30727085 0.69571349 0.55881479 1.        ]
 [1.         0.88907584 0.819365

In [7]:
import numpy as np

print("Extrayendo información específica con indexación avanzada de stock_prices_matrix:")

# Rendimiento de la primera acción (fila 0) en el tercer día (columna 2)
# La indexación en Python/NumPy comienza en 0
accion_1_dia_3 = stock_prices_matrix[0, 2]
print(f"\nPrecio de la Acción 1 en el Día 3: {accion_1_dia_3:.2f}")

# Rendimiento de la segunda acción (fila 1) en todos los días (todas las columnas)
accion_2_todos_dias = stock_prices_matrix[1, :]
print("\nPrecios de la Acción 2 en todos los días:")
print(accion_2_todos_dias)

# Rendimiento de todas las acciones en el cuarto día (columna 3)
todas_acciones_dia_4 = stock_prices_matrix[:, 3]
print("\nPrecios de todas las Acciones en el Día 4:")
print(todas_acciones_dia_4)

# Rendimiento de las primeras tres acciones (filas 0, 1, 2) durante los primeros dos días (columnas 0, 1)
sub_matriz_rendimiento = stock_prices_matrix[0:3, 0:2]
print("\nPrecios de las primeras 3 Acciones durante los primeros 2 Días:")
print(sub_matriz_rendimiento)

Extrayendo información específica con indexación avanzada de stock_prices_matrix:

Precio de la Acción 1 en el Día 3: 50.72

Precios de la Acción 2 en todos los días:
[51.9134767  51.80202026 51.73197532 50.9109288  50.9086781 ]

Precios de todas las Acciones en el Día 4:
[50.54495966 50.9109288  51.09204885 50.54003747 51.28403024]

Precios de las primeras 3 Acciones durante los primeros 2 Días:
[[49.82273951 50.2198607 ]
 [51.9134767  51.80202026]
 [50.28379341 49.5411254 ]]


In [8]:
import numpy as np

print("Demostrando Broadcasting con stock_prices_matrix:")

# --- Ejemplo 1: Sumar un valor constante a todos los precios ---
# Esto añade 5 a cada elemento de la matriz
constant_addition = stock_prices_matrix + 5
print("\nMatriz con un valor constante (5) sumado a cada elemento:")
print(constant_addition)

# --- Ejemplo 2: Multiplicar cada fila (acción) por un factor diferente ---
# Creamos un array unidimensional de factores, uno por cada acción (fila).
# stock_prices_matrix tiene 5 filas, así que necesitamos 5 factores.
factors = np.array([1.01, 0.98, 1.05, 0.99, 1.02]) # Factores arbitrarios

# NumPy automáticamente 'estira' el array de factores para que coincida
# con las filas de stock_prices_matrix y realiza la multiplicación.
# El array 'factors' se transmite a lo largo de las columnas.
scaled_prices = stock_prices_matrix * factors[:, np.newaxis]
print("\nMatriz donde cada acción (fila) ha sido multiplicada por un factor diferente:")
print(scaled_prices)

Demostrando Broadcasting con stock_prices_matrix:

Matriz con un valor constante (5) sumado a cada elemento:
[[54.82273951 55.2198607  55.72188949 55.54495966 56.11515368]
 [56.9134767  56.80202026 56.73197532 55.9109288  55.9086781 ]
 [55.28379341 54.5411254  55.31861097 56.09204885 56.64904125]
 [56.09377364 55.93227905 55.4836149  55.54003747 55.50789564]
 [55.1672223  55.43684225 55.142282   56.28403024 56.69071212]]

Matriz donde cada acción (fila) ha sido multiplicada por un factor diferente:
[[50.3209669  50.72205931 51.22910838 51.05040925 51.62630522]
 [50.87520717 50.76597985 50.69733581 49.89271022 49.89050454]
 [52.79798308 52.01818167 52.83454152 53.6466513  54.23149331]
 [50.58283591 50.42295626 49.97877875 50.03463709 50.00281669]
 [51.17056675 51.4455791  51.14512764 52.30971084 52.72452636]]


Comparacion entre Numpy y Python

Eficiencia codigo

Numpy: Conciso y legible, las operaciones se expresan a menudo en una sola línea utilizando funciones vectorizadas.

Python: Requiere el uso explícito de bucles (for) para la mayoría de las operaciones, especialmente en datos multidimensionales (listas anidadas).

Rendimiento Computacional

Numpy: Altamente optimizado, lo que permite que los cálculos se realicen mediante rutinas de bajo nivel precompiladas. Las operaciones de NumPy están vectorizadas, lo que significa que operan en arrays completos a la vez, eliminando la sobrecarga de los bucles de Python. Los arrays de NumPy almacenan los datos en bloques contiguos de memoria, lo que mejora el rendimiento de la caché y el acceso a la memoria. Muchas operaciones subyacentes de NumPy pueden aprovechar procesadores multi-núcleo o hardware especializado (como GPUs) para la computación paralela, aumentando aún más la velocidad.

Python: Las operaciones sobre listas de Python son generalmente mucho más lentas, especialmente para conjuntos de datos grandes, debido a que Python es un lenguaje interpretado y sus bucles se ejecutan secuencialmente. Almacenan referencias a objetos que pueden estar dispersos en la memoria, lo que es menos eficiente.

Conclusion

Para cálculos numéricos, especialmente con grandes conjuntos de datos y arrays/matrices multidimensionales, NumPy ofrece un rendimiento computacional vastamente superior y un código significativamente más eficiente, legible y conciso en comparación con la implementación de estas operaciones desde cero utilizando listas y bucles de Python puro. Es el estándar de facto para la computación numérica en Python por una razón.

# Análisis de Precios de Acciones con NumPy

Este notebook de Google Colab demuestra varias operaciones y análisis fundamentales utilizando la librería NumPy en Python, aplicado a un conjunto de datos simulado de precios de acciones.

## Contenido

1.  **Generación de Datos Simulados**: Creación de un array NumPy con precios de acciones simulados a lo largo del tiempo.
2.  **Organización en Matriz**: Transformación de una parte de los datos simulados en una matriz de 5x5 para representar precios de 5 acciones durante 5 días.
3.  **Estadísticas por Acción**: Cálculo de estadísticas básicas (promedio, máximo, mínimo) para cada acción (fila).
4.  **Variación Porcentual Diaria**: Determinación de los cambios porcentuales diarios en el precio de cada acción.
5.  **Funciones Matemáticas Avanzadas**: Aplicación de logaritmo natural, función exponencial y normalización Min-Max a la matriz de precios.
6.  **Indexación Avanzada**: Extracción de información específica de la matriz utilizando técnicas de indexación de NumPy.
7.  **Broadcasting**: Demostración de cómo NumPy aplica operaciones a arrays de diferentes formas de manera eficiente.
8.  **Comparación NumPy vs. Python Puro**: Una explicación de las ventajas de NumPy en términos de eficiencia de código y rendimiento computacional en comparación con las operaciones equivalentes en Python puro.

## Requisitos

Para ejecutar este notebook, solo necesitas tener instalado:

*   `numpy`

## Uso

Simplemente ejecuta las celdas en secuencia para ver cada paso del análisis. Puedes modificar los parámetros de simulación o experimentar con diferentes operaciones de NumPy.